### ISSUE TITLE
『「障害者」表記について』にリソースを追記してはどうか

### ISSUE THREAD

**Issue by momdo** [lifull/accessibility-guidelines#14]
https://lifull.github.io/accessibility-guidelines/introduction.html#%E9%9A%9C%E5%AE%B3%E8%80%85%E8%A1%A8%E8%A8%98%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

あえて表記について言及するのは何らかの意図があってのことかと思いますが、参考資料として下記を参照するのはどうでしょうか。

「障害」の表記に関する国語分科会の考え方（令和３年３月 12 日文化審議会国語分科会）
https://www.bunka.go.jp/seisaku/bunkashingikai/kokugo/hokoku/pdf/92880801_03.pdf

**Comment by tsmd** [comment]
メモ：次期バージョンで追加予定
