### ISSUE TITLE
「レベル3…できれば考慮」について

### ISSUE THREAD

**Issue by momdo** [lifull/accessibility-guidelines#15]
https://lifull.github.io/accessibility-guidelines/usage.html#%E3%83%AC%E3%83%99%E3%83%AB3%E3%81%A7%E3%81%8D%E3%82%8C%E3%81%B0%E8%80%83%E6%85%AE

> 達成することで、WCAGのA, AAの基準がおおむねカバーされます。

WCAGに触れるのであれば、「達成基準」という用語を使ったほうがよいと思います。
（単純に置換すると、「達成することで～達成基準…」となってしまい文章のすわりが悪くなってしまいますが。

**Comment by tsmd** [comment]
@momdo 
ありがとうございます！
ご指摘、ごもっともと思います。対応したいとおもいます～
