### ISSUE TITLE
「新しいタブで開くリンク」の参考情報について

### ISSUE THREAD

**Issue by momdo** [lifull/accessibility-guidelines#16]
https://lifull.github.io/accessibility-guidelines/design-forms-and-interactions.html#link-opens-in-new-tab

これについては、本筋としては[達成基準 3.2.5「要求による変化」](https://waic.jp/translations/WCAG21/Understanding/change-on-request)の話であって、
達成基準3.2.1「フォーカス時」や、達成基準3.2.2「入力時」については深く関係するわけでもないという理解でいます。
達成方法についてはG201というよりかはむしろ、[H83](https://waic.jp/translations/WCAG21/Techniques/html/H83)かもしれません。

**Comment by tsmd** [comment]
#39 の変更にて対応済みなので close します。
